---
underlay:
  infra_link_net: 10.198.0.0/16
  infra_lo_net: 10.199.0.0/16
  mgmt_lo_net: 10.100.3.0/24
evpn_spines:
  - hostname: eosdist
  - hostname: eosdist2
vrfs:
  - name: STUDENTS
    rd: "1:3"
    groups:
      - DIST
